### ISSUE TITLE
Insufficient Energy

### ISSUE THREAD

**Issue by Irishrobert** [vechain/thor-sync-wiki#8]
Dear,
Having a problem by sending Vechain from my Sync wallet  to my account on the trading platform.
![Insufficient Energy](https://user-images.githubusercontent.com/67845133/86522926-58434780-be65-11ea-9efc-37593c613367.png)

I add the recipient adress and the amount to send,after that I connect my ledger and in that frame
stated:Insuficient energy and than I cannot do nothing anymore.Hope you can help me.Regards
Robert

![image](https://user-images.githubusercontent.com/67845133/86522859-693f8900-be64-11ea-9bb9-5ad5e3167255.png)

**Comment by XJWX89** [comment]
hi @Irishrobert , base on the information you provided, your VTHO balance is not enough for paying the transaction fee. According to the VTHO generation formula , you need approximately one more day to get enough VTHO once the VTHO is enough. You can make the transfer. 

[VTHO calculator](https://vechainstats.com/vtho-calculator/)

**Comment by Irishrobert** [comment]
Thanks for the info.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
